
package gui;

import javax.swing.JOptionPane;
import logica.Usuario;
import percistencia.ControladorUsuario;

public class Eliminar_Usuario extends javax.swing.JInternalFrame {
    private ControladorUsuario cr;
    /**
     * Creates new form Eliminar_Usuario
     */
    public Eliminar_Usuario() {
        initComponents();
        cr = new ControladorUsuario();
    }
    public void limpiarcampos(){
        jTxt_Buscar_Usu.setText("");
        jTxt_IdUsuario_Eli.setText("");
        jTxt_Eliminar_Usu.setText("");
        jPass_Eliminar_Con.setText("");
        jTxt_Rol_Eliminar_Usu.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Eliminar_Usu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTxt_Buscar_Usu = new javax.swing.JTextField();
        jBtn_Buscar_Usu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTxt_IdUsuario_Eli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxt_Eliminar_Usu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPass_Eliminar_Con = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTxt_Rol_Eliminar_Usu = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ELIMINAR USUARIOS");

        jBtn_Eliminar_Usu.setText("Eliminar");
        jBtn_Eliminar_Usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Eliminar_UsuActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Usuario"));

        jLabel8.setText("Usuario:");

        jBtn_Buscar_Usu.setText("Buscar");
        jBtn_Buscar_Usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Buscar_UsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Buscar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Buscar_Usu)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxt_Buscar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Buscar_Usu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Usuario"));

        jLabel7.setText("Id_Usuario:");

        jTxt_IdUsuario_Eli.setEditable(false);

        jLabel4.setText("Usuario:");

        jTxt_Eliminar_Usu.setEditable(false);

        jLabel5.setText("Contraseña:");

        jPass_Eliminar_Con.setEditable(false);

        jLabel6.setText("Rol Empleado:");

        jTxt_Rol_Eliminar_Usu.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt_Eliminar_Usu)
                    .addComponent(jTxt_IdUsuario_Eli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPass_Eliminar_Con)
                    .addComponent(jTxt_Rol_Eliminar_Usu))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxt_IdUsuario_Eli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_Eliminar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPass_Eliminar_Con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxt_Rol_Eliminar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jBtn_Eliminar_Usu))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_Eliminar_Usu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_Eliminar_UsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Eliminar_UsuActionPerformed
        // Obtener el ID del usuario desde el campo de texto
    String idUsuarioText = jTxt_IdUsuario_Eli.getText();  // El campo donde almacenas el ID
    
    // Verificar que el campo de ID no esté vacío
    if (!idUsuarioText.isEmpty()) {
        try {
            // Convertir el ID a un entero
            int idUsuario = Integer.parseInt(idUsuarioText);
            
            // Crear un objeto Usuario con el ID a eliminar
            Usuario usuario = new Usuario();
            usuario.setId_usuario(idUsuario);

            // Mostrar un cuadro de confirmación antes de proceder
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, 
                    "¿Estás seguro que deseas eliminar al usuario con ID: " + idUsuario + "?", 
                    "Confirmar eliminación", 
                    JOptionPane.YES_NO_OPTION);

            // Si el usuario confirma la eliminación
            if (confirmacion == JOptionPane.YES_OPTION) {
                // Llamar al método para borrar el usuario en el controlador
                if (cr.borrarUsuario(usuario)) {
                    JOptionPane.showMessageDialog(rootPane, "Usuario eliminado con éxito", "Eliminación Usuario", JOptionPane.INFORMATION_MESSAGE);
                    limpiarcampos();  // Método para limpiar los campos del formulario
                } else {
                    limpiarcampos();
                    JOptionPane.showMessageDialog(rootPane, "Error al eliminar el usuario. Verifica el ID", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            limpiarcampos();
            // Si el ID no es un número válido, mostrar un mensaje de error
            JOptionPane.showMessageDialog(rootPane, "El ID ingresado no es válido", "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        limpiarcampos();
        // Mostrar mensaje si el campo de ID está vacío
        JOptionPane.showMessageDialog(rootPane, "Por favor, ingresa el ID del usuario a eliminar", "Error", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jBtn_Eliminar_UsuActionPerformed

    private void jBtn_Buscar_UsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Buscar_UsuActionPerformed
        Usuario temp = new Usuario();
        temp.setNombre_usuario(jTxt_Buscar_Usu.getText());
        cr.setUsuario(temp);

        if(cr.mostrarUsuario()){
            temp = cr.getUsuario();
            System.out.println(temp.getNombre_usuario());
            jTxt_IdUsuario_Eli.setText(String.valueOf(temp.getId_usuario()));
            jTxt_Eliminar_Usu.setText(temp.getNombre_usuario());
            jPass_Eliminar_Con.setText(temp.getContraseña_usuario());
            jTxt_Rol_Eliminar_Usu.setText(temp.getRol_empleado());
        }else{
            limpiarcampos();
            JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado, verificar los datos","Error de busqueda",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_Buscar_UsuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Buscar_Usu;
    private javax.swing.JButton jBtn_Eliminar_Usu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPass_Eliminar_Con;
    private javax.swing.JTextField jTxt_Buscar_Usu;
    private javax.swing.JTextField jTxt_Eliminar_Usu;
    private javax.swing.JTextField jTxt_IdUsuario_Eli;
    private javax.swing.JTextField jTxt_Rol_Eliminar_Usu;
    // End of variables declaration//GEN-END:variables
}
