
package gui;

import javax.swing.JOptionPane;
import logica.Usuario;
import percistencia.ControladorUsuario;

public class Modificar_Usuarios extends javax.swing.JInternalFrame {
    private ControladorUsuario cr;
    public Modificar_Usuarios() {
        initComponents();
        cr = new ControladorUsuario();
    }
    public void limpiarcampos(){
        jTxt_Buscar_Usu.setText("");
        jTxt_Modificar_Usu.setText("");
        jPass_Modificar_Con.setText("");
        jPass_Modificar_Con_Co.setText("");
        jTxt_Rol_Usuario.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Modificar_Usu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_Buscar_Usu = new javax.swing.JTextField();
        jBtn_Buscar_Usu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxt_Modificar_Usu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPass_Modificar_Con = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPass_Modificar_Con_Co = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTxt_Rol_Usuario = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ACTUALIZAR USUARIO");

        jBtn_Modificar_Usu.setText("Modificar");
        jBtn_Modificar_Usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Modificar_UsuActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Usuario"));

        jLabel1.setText("Usuario:");

        jBtn_Buscar_Usu.setText("Buscar");
        jBtn_Buscar_Usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Buscar_UsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Buscar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Buscar_Usu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_Buscar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Buscar_Usu))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar Usuario"));

        jLabel3.setText("Usuario:");

        jLabel5.setText("Contraseña:");

        jLabel4.setText("Contraseña Con.:");

        jLabel2.setText("Rol Empleado:");

        jTxt_Rol_Usuario.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPass_Modificar_Con_Co, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jPass_Modificar_Con)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jTxt_Rol_Usuario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(jTxt_Modificar_Usu)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_Modificar_Usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPass_Modificar_Con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPass_Modificar_Con_Co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTxt_Rol_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jBtn_Modificar_Usu)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Modificar_Usu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_Modificar_UsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Modificar_UsuActionPerformed
        Usuario temp;
    
    if (cr.getUsuario() != null) {
        temp = cr.getUsuario();
        String nuevoNombreUsuario = jTxt_Modificar_Usu.getText();
        
        // Validar que el nombre de usuario no esté vacío
        if (nuevoNombreUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El nombre de usuario no puede estar vacío", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;  // Detener el proceso si el nombre está vacío
        }
        // Asignar el nuevo nombre de usuario al objeto
        temp.setNombre_usuario(nuevoNombreUsuario);

        // Obtener las nuevas contraseñas desde los campos
        char[] passwordArray = jPass_Modificar_Con.getPassword();
        char[] confirmPasswordArray = jPass_Modificar_Con_Co.getPassword();
        
        String nuevaContraseña = new String(passwordArray);
        String confirmarContraseña = new String(confirmPasswordArray);

        // Verificar que la contraseña no esté vacía y tenga al menos 6 caracteres
        if (nuevaContraseña.isEmpty() || nuevaContraseña.length() < 6) {
            limpiarcampos();
            JOptionPane.showMessageDialog(rootPane, "La contraseña debe tener al menos 6 caracteres", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;  // Detener el proceso si la contraseña es inválida
        }

        // Verificar si ambas contraseñas coinciden
        if (!nuevaContraseña.equals(confirmarContraseña)) {
            limpiarcampos();
            JOptionPane.showMessageDialog(rootPane, "Las contraseñas no coinciden", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;  // Detener el proceso si las contraseñas no coinciden
        }

        // Asignar la nueva contraseña al usuario
        temp.setContraseña_usuario(nuevaContraseña);

        // Actualizar el usuario en la base de datos o archivo
        if (cr.actualizar(temp)) {
            JOptionPane.showMessageDialog(rootPane, "Datos actualizados con éxito", "Actualización Usuario", JOptionPane.INFORMATION_MESSAGE);
            limpiarcampos();
        } else {
            limpiarcampos();
            JOptionPane.showMessageDialog(rootPane, "Error al actualizar los datos, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        limpiarcampos();
        JOptionPane.showMessageDialog(rootPane, "Error: Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jBtn_Modificar_UsuActionPerformed

    private void jBtn_Buscar_UsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Buscar_UsuActionPerformed
        Usuario temp = new Usuario();
        temp.setNombre_usuario(jTxt_Buscar_Usu.getText());
        cr.setUsuario(temp);

        if(cr.mostrarUsuario()){
            temp = cr.getUsuario();
            System.out.println(temp.getNombre_usuario());
            jTxt_Modificar_Usu.setText(temp.getNombre_usuario());
            jPass_Modificar_Con.setText(temp.getContraseña_usuario());
            jPass_Modificar_Con_Co.setText(temp.getContraseña_usuario());
            jTxt_Rol_Usuario.setText(temp.getRol_empleado());
        }else{
            limpiarcampos();
            JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado, verificar los datos","Error de busqueda",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_Buscar_UsuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Buscar_Usu;
    private javax.swing.JButton jBtn_Modificar_Usu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPass_Modificar_Con;
    private javax.swing.JPasswordField jPass_Modificar_Con_Co;
    private javax.swing.JTextField jTxt_Buscar_Usu;
    private javax.swing.JTextField jTxt_Modificar_Usu;
    private javax.swing.JTextField jTxt_Rol_Usuario;
    // End of variables declaration//GEN-END:variables
}
