package gui;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import percistencia.ControladorUsuario;

public class Registro_Usuarios extends javax.swing.JInternalFrame {
    private char[] password_temp;
    private boolean password_ok;
    private ControladorUsuario cr;
    
    public Registro_Usuarios() {
        initComponents();
        cr = new ControladorUsuario();
    }
    public void limpiarcampos(){
        jTxt_Usuario_R.setText("");
        jPass_Usuario_Re.setText("");
        jPass_Usuario_Re_Co.setText("");
        jTxt_Rol_Usuario.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxt_Usuario_R = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtn_Registrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxt_Rol_Usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPass_Usuario_Re = new javax.swing.JPasswordField();
        jPass_Usuario_Re_Co = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("REGISTRO USUARIOS");

        jLabel1.setText("Usuario:");

        jBtn_Registrar.setText("Registrar");
        jBtn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RegistrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña:");

        jLabel4.setText("Rol:");

        jLabel5.setText("Conf. Contraseña:");

        jPass_Usuario_Re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPass_Usuario_ReActionPerformed(evt);
            }
        });
        jPass_Usuario_Re.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPass_Usuario_ReKeyReleased(evt);
            }
        });

        jPass_Usuario_Re_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPass_Usuario_Re_CoActionPerformed(evt);
            }
        });
        jPass_Usuario_Re_Co.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPass_Usuario_Re_CoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_Registrar)
                    .addComponent(jTxt_Usuario_R)
                    .addComponent(jTxt_Rol_Usuario)
                    .addComponent(jPass_Usuario_Re)
                    .addComponent(jPass_Usuario_Re_Co, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Usuario_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPass_Usuario_Re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPass_Usuario_Re_Co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Rol_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addComponent(jBtn_Registrar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPass_Usuario_ReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPass_Usuario_ReActionPerformed
        
    }//GEN-LAST:event_jPass_Usuario_ReActionPerformed

    private void jPass_Usuario_Re_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPass_Usuario_Re_CoActionPerformed
        
    }//GEN-LAST:event_jPass_Usuario_Re_CoActionPerformed

    private void jBtn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RegistrarActionPerformed
        String nombre_usuario, contraseña_usuario, rol_empleado;
        nombre_usuario = jTxt_Usuario_R.getText();
        rol_empleado = jTxt_Rol_Usuario.getText();

        if (password_temp != null) {
            contraseña_usuario = new String(password_temp);

            if (!nombre_usuario.equals("") && !rol_empleado.equals("") && password_ok) {
                // Intentar insertar el usuario
                if (cr.insertar(nombre_usuario, contraseña_usuario, rol_empleado)) {
                    limpiarcampos();
                    JOptionPane.showMessageDialog(rootPane, "Se registró usuario");
                } else {
                    limpiarcampos();
                    JOptionPane.showMessageDialog(rootPane, "El nombre de usuario ya existe");
                }
            } else {
                limpiarcampos();
                JOptionPane.showMessageDialog(rootPane, "Tiene que ingresar el usuario y contraseña");
            }
        } else {
            limpiarcampos();
            JOptionPane.showMessageDialog(rootPane, "Contraseñas no coiciden");
        }
    }//GEN-LAST:event_jBtn_RegistrarActionPerformed

    private void jPass_Usuario_ReKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPass_Usuario_ReKeyReleased
        password_temp = jPass_Usuario_Re.getPassword();
    }//GEN-LAST:event_jPass_Usuario_ReKeyReleased

    private void jPass_Usuario_Re_CoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPass_Usuario_Re_CoKeyReleased
        char[]temp;
        temp = jPass_Usuario_Re_Co.getPassword();
        
        if(Arrays.compare(temp,password_temp)==0){
            password_ok = true;
            jPass_Usuario_Re_Co.setBorder(new JPasswordField().getBorder());
        }else{
            password_ok = false;
            jPass_Usuario_Re_Co.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
        }
    }//GEN-LAST:event_jPass_Usuario_Re_CoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPass_Usuario_Re;
    private javax.swing.JPasswordField jPass_Usuario_Re_Co;
    private javax.swing.JTextField jTxt_Rol_Usuario;
    private javax.swing.JTextField jTxt_Usuario_R;
    // End of variables declaration//GEN-END:variables
}
